// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sut.unun.domain;

import com.sut.unun.domain.Chili;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Chili_Roo_Configurable {
    
    declare @type: Chili: @Configurable;
    
}
